// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxjgeN0Aw9gCGE_6YlOO58uP6Iu7SxlgM',
    appId: '1:237096137001:web:3095821e2c5809f7878738',
    messagingSenderId: '237096137001',
    projectId: 'flutter-proj-5370e',
    authDomain: 'flutter-proj-5370e.firebaseapp.com',
    databaseURL: 'https://flutter-proj-5370e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-proj-5370e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeriHhs0BJ5woyCYyzQYoAu9AQyLvXm5o',
    appId: '1:237096137001:android:f28eec38ad5e5a76878738',
    messagingSenderId: '237096137001',
    projectId: 'flutter-proj-5370e',
    databaseURL: 'https://flutter-proj-5370e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-proj-5370e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1jvcimJOBAh6-Yk4h6_gBSBGhP7yi8BA',
    appId: '1:237096137001:ios:a188fffacaa9b8b6878738',
    messagingSenderId: '237096137001',
    projectId: 'flutter-proj-5370e',
    databaseURL: 'https://flutter-proj-5370e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-proj-5370e.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1jvcimJOBAh6-Yk4h6_gBSBGhP7yi8BA',
    appId: '1:237096137001:ios:a188fffacaa9b8b6878738',
    messagingSenderId: '237096137001',
    projectId: 'flutter-proj-5370e',
    databaseURL: 'https://flutter-proj-5370e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-proj-5370e.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxjgeN0Aw9gCGE_6YlOO58uP6Iu7SxlgM',
    appId: '1:237096137001:web:dccd0d324622977f878738',
    messagingSenderId: '237096137001',
    projectId: 'flutter-proj-5370e',
    authDomain: 'flutter-proj-5370e.firebaseapp.com',
    databaseURL: 'https://flutter-proj-5370e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-proj-5370e.firebasestorage.app',
  );
}
